from libs.gearprofile import *
from abaqus import *
from abaqusConstants import *

backwardCompatibility.setValues(includeDeprecated=True, reportDeprecated=False)

myModel = mdb.Model(name='{{model_name}}')

pinion_formcoords = {{ pair[0].formcoords }}
wheel_formcoords = {{ pair[1].formcoords }}
pinion_shaftcoords = {{ pair[0].shaftcoords }}
wheel_shaftcoords = {{ pair[1].shaftcoords }}


#PINION
myPinionSketch = myModel.ConstrainedSketch(name='Pinion sketch', sheetSize=400.0)
pinion_profile = myPinionSketch.Spline(points=pinion_formcoords)
pinion_tooth1 = myPinionSketch.ConstructionLine(point1=pinion_shaftcoords[0],point2=pinion_formcoords[-1])
pinion_tooth2 = myPinionSketch.Line(point1=pinion_shaftcoords[-1], point2=pinion_formcoords[0])
pinion_shaft = myPinionSketch.ArcByCenterEnds(center=({{ pair[0].rotate_x }}, {{ pair[0].rotate_y }}), point1=pinion_shaftcoords[0],point2=pinion_shaftcoords[-1])
myPinionSketch.rotate(centerPoint=({{ pair[0].rotate_x }}, {{ pair[0].rotate_y }},), angle={{ pair[0].rotate_ang }},objectList=(pinion_profile, pinion_tooth2, pinion_tooth1, pinion_shaft,))
myPinionSketch.copyMirror(mirrorLine=pinion_tooth1, objectList=(pinion_profile, pinion_tooth2, pinion_shaft,))
pinion_tooth_part = myModel.Part(name='Pinion', dimensionality=THREE_D, type=DEFORMABLE_BODY)
pinion_tooth_part.BaseSolidExtrude(sketch=myPinionSketch, depth={{ pair[0].data.b }})

#WHEEL
myGearSketch = myModel.ConstrainedSketch(name='Gear sketch', sheetSize=400.0)
gear_profile = myGearSketch.Spline(points=wheel_formcoords)
gear_tooth1 = myGearSketch.ConstructionLine(point1=wheel_shaftcoords[0], point2=wheel_formcoords[-1])
gear_tooth2 = myGearSketch.Line(point1=wheel_shaftcoords[-1], point2=wheel_formcoords[0])
gear_shaft = myGearSketch.ArcByCenterEnds(center=({{ pair[1].rotate_x }}, {{ pair[1].rotate_y }}), point1=wheel_shaftcoords[0],point2=wheel_shaftcoords[-1])
myGearSketch.rotate(centerPoint=({{ pair[1].rotate_x }}, {{ pair[1].rotate_y }}), angle={{ pair[0].rotate_ang }},objectList=(gear_profile, gear_tooth2, gear_tooth1,gear_shaft))
myGearSketch.copyMirror(mirrorLine=gear_tooth1, objectList=(gear_profile, gear_tooth2, gear_shaft,))
gear_tooth_part = myModel.Part(name='Gear', dimensionality=THREE_D, type=DEFORMABLE_BODY)
gear_tooth_part.BaseSolidExtrude(sketch=myGearSketch, depth={{ pair[1].data.b }})